# -*- coding: utf-8 -*-
"""m2_c1_Jakbaraliyev

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UNUCXYHwq82jHZJd42IwwrpXcmvHD1t
"""

print("hello, Ai/ML")

age = 21
gpa = 4.65
name = "Akbarali"
is_student = True
scores = [89, 92, 98, 95, 88]

print(age, type(age))
print(gpa, type(gpa))
print(name, type(name))
print(is_student, type(is_student))
print(scores, type(scores))

def calculate_average(numbers):
    total = sum(numbers)
    count = len(numbers)
    return total / count

test1 = [80, 90, 70, 85, 95]
test2 = [55, 62, 48, 71]

print("Average 1:", calculate_average(test1))
print("Average 2:", calculate_average(test2))

cities = ["Tashkent", "Samarkand", "Bukhara", "Namangan", "Fergana"]

for index, city in enumerate(cities):
    print(f"Index {index}: {city}")

import random

# 10 ta tasodifiy ball yaratish
exam_scores = [random.randint(0, 100) for _ in range(10)]
print("Scores:", exam_scores)

# O'rtacha ballni hisoblash
avg = calculate_average(exam_scores)
print(f"Class average: {avg:.1f}")

# Natijani tekshirish
if avg >= 60:
    print("Result: PASS")
else:
    print("Result: FAIL")